// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDvUeftX4heC3mWomIvQgBL1fBh_G7q_k',
    appId: '1:826611494872:web:83381afd6d4562f29b0cad',
    messagingSenderId: '826611494872',
    projectId: 'my-chat-app-e1546',
    authDomain: 'my-chat-app-e1546.firebaseapp.com',
    storageBucket: 'my-chat-app-e1546.firebasestorage.app',
    measurementId: 'G-FBVGYZ9T6Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANk5zXMKZvHqM5omofRn-oPg-8v4HG_dk',
    appId: '1:826611494872:ios:c9f87cf17bdd17769b0cad',
    messagingSenderId: '826611494872',
    projectId: 'my-chat-app-e1546',
    storageBucket: 'my-chat-app-e1546.firebasestorage.app',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDvUeftX4heC3mWomIvQgBL1fBh_G7q_k',
    appId: '1:826611494872:web:5467106f4a0d055c9b0cad',
    messagingSenderId: '826611494872',
    projectId: 'my-chat-app-e1546',
    authDomain: 'my-chat-app-e1546.firebaseapp.com',
    storageBucket: 'my-chat-app-e1546.firebasestorage.app',
    measurementId: 'G-6BGM9M61VX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANk5zXMKZvHqM5omofRn-oPg-8v4HG_dk',
    appId: '1:826611494872:ios:c9f87cf17bdd17769b0cad',
    messagingSenderId: '826611494872',
    projectId: 'my-chat-app-e1546',
    storageBucket: 'my-chat-app-e1546.firebasestorage.app',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd2blzzfPPaNxeNcTjhAkbPTtcleTyNWg',
    appId: '1:826611494872:android:cd55ea64fdb3d9799b0cad',
    messagingSenderId: '826611494872',
    projectId: 'my-chat-app-e1546',
    storageBucket: 'my-chat-app-e1546.firebasestorage.app',
  );

}